export const fonts = {
	cardTitle: {
		fontFamily: "Unbounded",
		fontSize: "20px",
		fontStyle: "normal",
		fontWeight: 500,
		lineHeight: "135%",
	},
	cardPrice: {
		fontFamily: "Unbounded",
		fontSize: "20px",
		fontStyle: "normal",
		fontWeight: 400,
		lineHeight: "135%",
	},
	primaryBtn: {
		fontFamily: "Unbounded",
		fontSize: "16px",
		fontStyle: "normal",
		fontWeight: 500,
		lineHeight: "150%",
		letterSpacing: "0.64px",
	},
	textOrder: {
		fontFamily: "Open Sans",
		fontSize: "16px",
		fontStyle: "normal",
		fontWeight: 500,
		lineHeight: "135%",
	},
	secondaryBtn: {
		fontFamily: "Unbounded",
		fontSize: "12px",
		fontStyle: "normal",
		fontWeight: 600,
		lineHeight: "120%",
		letterSpacing: "0.48px",
	},
	title: {
		fontFamily: "Unbounded",
		fontSize: "60px",
		fontStyle: "normal",
		fontWeight: 700,
		lineHeight: "120%",
	},
};
