version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.develop
    restart: always
    volumes:
      - ./app/build:/var/www
    ports:
      - 8085:80
    networks:
      - web

networks:
  web:

